# Generated by Django 5.0.7 on 2024-10-16 09:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_trends', '0002_alter_markettrendspage_market_trends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettrendspage',
            name='market_trends',
            field=wagtail.fields.StreamField([('awards_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))]))], blank=True, null=True),
        ),
    ]
