# Generated by Django 5.0.7 on 2024-10-18 09:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_trends', '0003_alter_markettrendspage_market_trends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettrendspage',
            name='market_trends',
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
    ]
