# Generated by Django 5.0.7 on 2024-10-11 12:07

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspage_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='more_news_heading',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='news_heading',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news',
            field=wagtail.fields.StreamField([('news_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('posted_date', wagtail.blocks.CharBlock(help_text='Posted date', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))]), help_text='Add multiple news to this section', label='Add text card'))]))], blank=True, null=True),
        ),
    ]
