# Generated by Django 5.0.7 on 2024-10-08 11:37

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Developer Index Page',
                'verbose_name_plural': 'Developer Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DeveloperPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_heading', models.CharField(max_length=255)),
                ('developer_details', wagtail.fields.StreamField([('developer_detail', wagtail.blocks.StructBlock([('content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('description', wagtail.blocks.CharBlock(max_length=500)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))), ('faq', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add sub heading', required=False)), ('points', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(help_text='Add your question', required=True)), ('answer', wagtail.blocks.RichTextBlock(editor='secondary', help_text='Add your answer', required=False))]), help_text='Add frequently asked questions to this section', label='Add FAQ'))], help_text='Add FAQs section', required=False))]))], blank=True, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_banner_image', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Developer Page',
                'verbose_name_plural': 'Developer Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
