# Generated by Django 5.0.7 on 2024-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_developerpage_developer_detail_page_and_more'),
        ('masters', '0003_alter_developer_price_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerpage',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developer_pages', to='masters.developer'),
        ),
    ]
