# Generated by Django 5.0.7 on 2024-10-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_developerpage_developers'),
        ('masters', '0003_alter_developer_price_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerpage',
            name='developers',
        ),
        migrations.AddField(
            model_name='developerpage',
            name='developers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_pages', to='masters.developer'),
        ),
    ]
