# Generated by Django 5.0.7 on 2024-10-09 11:33

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_remove_developerpage_developers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerpage',
            name='developer_detail_page',
            field=wagtail.fields.StreamField([('detail_content', wagtail.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add sub heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add description in table format', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerpage',
            name='developer_details',
            field=wagtail.fields.StreamField([('developer_detail', wagtail.blocks.StructBlock([('description_icons', wagtail.blocks.StructBlock([('descriptions', wagtail.blocks.StreamBlock([('description', wagtail.blocks.RichTextBlock(help_text='Add a description', required=True))], max_num=10, min_num=1)), ('icons', wagtail.blocks.StreamBlock([('icon', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an icon image', required=True))]))], max_num=10, min_num=1))])), ('faq', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add sub heading', required=False)), ('points', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(help_text='Add your question', required=True)), ('answer', wagtail.blocks.RichTextBlock(editor='default', help_text='Add your answer', required=False))]), help_text='Add frequently asked questions to this section', label='Add FAQ'))], help_text='Add FAQs section', required=False))]))], blank=True, null=True),
        ),
    ]
