# Generated by Django 5.0.7 on 2024-10-11 12:07

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_podcastpage_podcast_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastpage',
            name='podcast',
            field=wagtail.fields.StreamField([('podcast_block', wagtail.blocks.StructBlock([('video', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=True)), ('video_source', wagtail.blocks.ChoiceBlock(choices=[('upload', 'Upload Video'), ('external', 'External Video Link')], help_text='Choose whether to upload a video or provide an external link.', label='Video Source')), ('uploaded_video', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload a video file (MP4, MOV, AVI, or WebM)', label='Upload Video', required=False)), ('external_video_link', wagtail.blocks.URLBlock(help_text='Paste the URL of an external video (e.g., YouTube, Vimeo)', label='External Video Link', required=False)), ('watch_time', wagtail.blocks.IntegerBlock(help_text='Estimated time to watch/read the content.', label='Watch Time (minutes)', required=True)), ('proficiency_level', wagtail.blocks.ChoiceBlock(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Select the difficulty level.', label='Proficiency Level')), ('thumbnail', wagtail.images.blocks.ImageChooserBlock(help_text='Choose a thumbnail image for the video.', label='Thumbnail Image')), ('link_label', wagtail.blocks.CharBlock(help_text='The text for the link button.', label='Link Label', max_length=50, required=False))]), help_text='Add multiple video cards to this section', label='Add text card')), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False)), ('posted_date', wagtail.blocks.CharBlock(help_text='Posted date', required=True))]))], blank=True, null=True),
        ),
    ]
