# Generated by Django 5.0.7 on 2024-10-18 09:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcastpage_podcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastpage',
            name='podcast',
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastpage',
            name='podcast_intro',
            field=wagtail.fields.StreamField([]),
        ),
    ]
