# Generated by Django 5.0.7 on 2024-10-04 05:53

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category Index Page',
                'verbose_name_plural': 'Category Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(max_length=250)),
                ('facilities', wagtail.fields.StreamField([('category_facilities', wagtail.blocks.StructBlock([('category', wagtail.blocks.CharBlock(max_length=250)), ('sub_category', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('sub_category', wagtail.blocks.CharBlock(max_length=250))])))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category Page',
                'verbose_name_plural': 'Category Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
