# Generated by Django 5.0.7 on 2024-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorypage',
            old_name='facilities',
            new_name='category_details',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='heading',
        ),
        migrations.AddField(
            model_name='categorypage',
            name='property_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=10),
        ),
    ]
