# Generated by Django 5.0.7 on 2024-10-04 06:02

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_property', '0002_rename_facilities_categorypage_category_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='category_details',
            field=wagtail.fields.StreamField([('category_facilities', wagtail.blocks.StructBlock([('property_type', wagtail.blocks.ChoiceBlock(choices=[('rent', 'Rent'), ('buy', 'Buy')])), ('category', wagtail.blocks.CharBlock(max_length=250)), ('sub_category', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('sub_category', wagtail.blocks.CharBlock(max_length=250))])))]))], blank=True, null=True),
        ),
    ]
