# Generated by Django 5.0.7 on 2024-10-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_property', '0003_alter_categorypage_category_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='property_type',
        ),
    ]
