# Generated by Django 5.0.7 on 2024-10-11 10:45

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_type', models.CharField(blank=True, help_text='SEO Type', max_length=255)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('canonical_url', models.CharField(blank=True, help_text='Canonical URL for this page', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Optional. Alternative text for the OG title.', max_length=255)),
                ('og_description', models.CharField(blank=True, help_text='Optional. Alternative text for the OG description.', max_length=255)),
                ('banner_heading', models.CharField(default='', help_text='Banner heading', max_length=250, verbose_name='Banner heading')),
                ('banner_subheading', models.CharField(blank=True, default='', help_text='Banner sub heading', max_length=250, null=True, verbose_name='Banner sub heading')),
                ('banner_description', wagtail.fields.RichTextField(blank=True, help_text='Banner description', verbose_name='Banner description')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('banner_header_image', models.ForeignKey(blank=True, help_text='Banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Awards Index Page',
                'verbose_name_plural': 'Awards Index Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='AwardsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_type', models.CharField(blank=True, help_text='SEO Type', max_length=255)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('canonical_url', models.CharField(blank=True, help_text='Canonical URL for this page', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Optional. Alternative text for the OG title.', max_length=255)),
                ('og_description', models.CharField(blank=True, help_text='Optional. Alternative text for the OG description.', max_length=255)),
                ('banner_heading', models.CharField(default='', help_text='Banner heading', max_length=250, verbose_name='Banner heading')),
                ('banner_subheading', models.CharField(blank=True, default='', help_text='Banner sub heading', max_length=250, null=True, verbose_name='Banner sub heading')),
                ('banner_description', wagtail.fields.RichTextField(blank=True, help_text='Banner description', verbose_name='Banner description')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Heading')),
                ('awards', wagtail.fields.StreamField([('awards_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))]))])),
                ('accolades_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Heading')),
                ('accolades', wagtail.fields.StreamField([('accolades_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))]))])),
                ('banner_header_image', models.ForeignKey(blank=True, help_text='Banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Awards Page',
                'verbose_name_plural': 'Awards Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='AwardsPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='events_awards.awardspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='awardspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='events_awards.AwardsPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
