# Generated by Django 5.0.7 on 2024-10-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardspage',
            name='accolades_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Accolades Heading'),
        ),
    ]
