# Generated by Django 5.0.7 on 2024-10-18 09:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_awards', '0004_alter_awardspage_accolades_alter_awardspage_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardspage',
            name='accolades',
        ),
        migrations.RemoveField(
            model_name='awardspage',
            name='accolades_heading',
        ),
        migrations.AlterField(
            model_name='awardspage',
            name='awards',
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
    ]
