# Generated by Django 5.0.7 on 2024-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_awards', '0006_remove_awardspage_awards_remove_awardspage_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardspage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Award description'),
        ),
    ]
