# Generated by Django 5.0.7 on 2024-10-11 11:43

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportpage_report_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='content',
            field=wagtail.fields.StreamField([('report_content_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=True)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('industried', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('points', wagtail.blocks.CharBlock(help_text='Add your points', required=True))]), help_text='Add multiple points to this section', label='Add industries'))], group='Base Blocks')), ('report_related_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=True)), ('related_news', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False))]), help_text='Add related news to this section', label='Add pages'))], group='Base Blocks'))], blank=True, null=True),
        ),
    ]
