# Generated by Django 5.0.7 on 2024-10-18 09:19

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reportpage_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpage',
            name='content',
            field=wagtail.fields.StreamField([('report_related_news_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('related_news', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False))]), help_text='Add related news to this section', label='Add pages'))], group='Base Blocks'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpage',
            name='reports',
            field=wagtail.fields.StreamField([], blank=True, null=True),
        ),
    ]
