# Generated by Django 5.0.7 on 2024-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_reportpage_report_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='reading_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Read Time'),
        ),
    ]
