# Generated by Django 5.0.7 on 2024-09-26 12:41

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiespage',
            name='facilities',
            field=wagtail.fields.StreamField([('amenities_facilities', wagtail.blocks.StructBlock([('facilities_amenities', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=250, required=False))])))]))], blank=True, null=True),
        ),
    ]
