# Generated by Django 5.0.7 on 2024-10-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0006_alter_bloglinkpage_content_alter_contentpage_content'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglinkpage',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='Select an internal page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
