# Generated by Django 5.0.7 on 2024-10-11 11:52

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_careerpage_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('career_content_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add your sub heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))], group='Base Blocks'))]),
        ),
    ]
