# Generated by Django 5.0.7 on 2024-10-16 09:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_careerpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='careers',
            field=wagtail.fields.StreamField([('career_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('location', wagtail.blocks.CharBlock(help_text='Add your location', required=False)), ('time', wagtail.blocks.CharBlock(help_text='Posted time', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='intro_heading',
            field=wagtail.fields.StreamField([('intro_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
