# Generated by Django 5.0.7 on 2024-10-18 09:19

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_careerpage_careers_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='careers',
        ),
        migrations.RemoveField(
            model_name='careerpage',
            name='intro_heading',
        ),
        migrations.RemoveField(
            model_name='careerpage',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='careerpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Career image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='posted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('career_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='secondary', help_text='Add additional text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))], group='Base Blocks')), ('career_opening_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add sub heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))], group='Base Blocks'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Career heading'),
        ),
    ]
