# Generated by Django 5.0.7 on 2024-10-18 09:20

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_remove_careerpage_careers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('career_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))], group='Base Blocks')), ('career_opening_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Add your heading', required=False)), ('sub_heading', wagtail.blocks.CharBlock(help_text='Add sub heading', required=False)), ('description', wagtail.blocks.RichTextBlock(editor='default', help_text='Add additional text', required=False))], group='Base Blocks'))], blank=True, null=True),
        ),
    ]
