# Generated by Django 5.0.7 on 2024-10-03 12:38

import off_plan_projects.models
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_plan_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippets', wagtail.fields.StreamField([('developer_snippet', wagtail.blocks.StructBlock([('snippet', wagtail.blocks.ChooserBlock(off_plan_projects.models.DeveloperSnippet, label='Developer Snippet'))]))])),
            ],
        ),
    ]
