# Generated by Django 5.0.7 on 2024-10-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off_plan_projects', '0002_projectpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developersnippet',
            name='content',
        ),
    ]
