# Generated by Django 5.0.7 on 2024-10-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_plan_projects', '0003_remove_developersnippet_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
                ('category_content', models.TextField(max_length=255)),
            ],
        ),
    ]
