# Generated by Django 5.0.7 on 2024-09-19 13:06

import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNewIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Property New Index Page',
                'verbose_name_plural': 'Property New Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PropertyNewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('commercial_floor', 'Commercial-Floors'), ('duplexs', 'Duplexs'), ('hotel_apartments', 'Hotel-Apartments'), ('offices', 'Offices'), ('penthouses', 'Penthouses')], max_length=20, null=True)),
                ('type_choice', models.CharField(blank=True, choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('currency_type', models.CharField(blank=True, choices=[('aed', 'AED'), ('bhd', 'BHD'), ('kwd', 'KWD'), ('omr', 'OMR'), ('qar', 'QAR'), ('sar', 'SAR')], max_length=20, null=True)),
                ('property_title', models.CharField(blank=True, max_length=250, null=True)),
                ('property', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('bedroom_count', models.CharField(blank=True, max_length=250, null=True)),
                ('bathroom_count', models.CharField(blank=True, max_length=250, null=True)),
                ('plot', models.CharField(blank=True, max_length=250, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=250, null=True)),
                ('call_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('mortgage_description', models.CharField(blank=True, max_length=250, null=True)),
                ('sale_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('bua_plot', models.CharField(blank=True, max_length=250, null=True)),
                ('plot_sqft', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=20, null=True)),
                ('description_title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('maid_apartment_title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', wagtail.fields.StreamField([('property_new_block', wagtail.blocks.StructBlock([('property_media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('media_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('video', 'Video')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))), ('maid_apartment_content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('content_data', wagtail.blocks.CharBlock(max_length=250, required=False))])))]))])),
            ],
            options={
                'verbose_name': 'Property New Page',
                'verbose_name_plural': 'Property New Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
