# Generated by Django 5.0.7 on 2024-09-19 13:25

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertynewpage',
            name='content',
            field=wagtail.fields.StreamField([('property_new_block', wagtail.blocks.StructBlock([('property_media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('media_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('video', 'Video')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=False))])))])), ('property_new_maid_content_block', wagtail.blocks.StructBlock([('maid_apartment_content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('content_data', wagtail.blocks.CharBlock(max_length=250, required=False))])))]))]),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('pending', 'Pending'), ('inprogress', 'Inprogress')], max_length=20, null=True),
        ),
    ]
