# Generated by Django 5.0.7 on 2024-09-20 04:26

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0002_alter_propertynewpage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertynewpage',
            name='content',
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='image_content',
            field=wagtail.fields.StreamField([('property_new_block', wagtail.blocks.StructBlock([('property_media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('media_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('video', 'Video')])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='maid_content',
            field=wagtail.fields.StreamField([('property_new_maid_content_block', wagtail.blocks.StructBlock([('maid_apartment_content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('content_data', wagtail.blocks.CharBlock(max_length=250, required=False))])))]))], blank=True, null=True),
        ),
    ]
