# Generated by Django 5.0.7 on 2024-09-23 12:02

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0003_remove_propertynewpage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynewpage',
            name='data_block',
            field=wagtail.fields.StreamField([('data_block', wagtail.blocks.StructBlock([('data_content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('content', wagtail.blocks.CharBlock(max_length=250, required=False))])))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='location_block',
            field=wagtail.fields.StreamField([('location_block', wagtail.blocks.StructBlock([('location_name', wagtail.blocks.CharBlock(max_length=250, required=False)), ('latitude', wagtail.blocks.CharBlock(max_length=250, required=False)), ('longitude', wagtail.blocks.CharBlock(max_length=250, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='currency_type',
            field=models.CharField(blank=True, choices=[('1', 'AED'), ('2', 'BHD'), ('3', 'KWD'), ('4', 'OMR'), ('5', 'QAR'), ('6', 'SAR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='image_content',
            field=wagtail.fields.StreamField([('property_new_block', wagtail.blocks.StructBlock([('property_media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('media_type', wagtail.blocks.ChoiceBlock(choices=[('image', 'Image'), ('video', 'Video')])), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('is_base', wagtail.blocks.BooleanBlock(default=False, required=False))]), required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='property_type',
            field=models.CharField(blank=True, choices=[('1', 'Apartment'), ('2', 'Commercial-Floors'), ('3', 'Duplexs'), ('4', 'Hotel-Apartments'), ('5', 'Offices'), ('6', 'Penthouses')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'Pending'), ('3', 'Inprogress')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='type_choice',
            field=models.CharField(blank=True, choices=[('1', 'Rent'), ('2', 'Buy')], max_length=20, null=True),
        ),
    ]
