# Generated by Django 5.0.7 on 2024-09-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0005_propertynewpage_is_favourite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertynewpage',
            name='is_favourite',
        ),
        migrations.CreateModel(
            name='FavouriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_new.propertynewpage')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
