# Generated by Django 5.0.7 on 2024-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0007_alter_favouriteproperty_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynewpage',
            name='mortgage_duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='mortgage_duration_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
