# Generated by Django 5.0.7 on 2024-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0008_propertynewpage_mortgage_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertynewpage',
            name='mortgage_duration_type',
            field=models.CharField(blank=True, choices=[('1', 'Months'), ('2', 'Years')], max_length=20, null=True),
        ),
    ]
