# Generated by Django 5.0.7 on 2024-10-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_property', '0004_remove_categorypage_property_type'),
        ('property_new', '0010_alter_propertynewpage_image_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynewpage',
            name='category_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='category_property.categorypage'),
        ),
    ]
