# Generated by Django 5.0.7 on 2024-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_new', '0011_propertynewpage_category_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertynewpage',
            name='category_page',
        ),
        migrations.RemoveField(
            model_name='propertynewpage',
            name='type_choice',
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propertynewpage',
            name='sub_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertynewpage',
            name='property_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=20, null=True),
        ),
    ]
