# Generated by Django 5.0.7 on 2024-10-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_property', '0004_remove_categorypage_property_type'),
        ('property_new', '0013_remove_propertynewpage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynewpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_property.categorypage'),
        ),
    ]
